-- ==========================================
-- User table — production-ready, sharding-friendly
-- ==========================================
-- Sharding design:
--   1. `id` is BIGINT (NOT auto-increment), generated by a distributed ID
--      algorithm (e.g. snowflake, segment).  Shard key = id % N.
--   2. Unique indexes are LOCAL to each shard; cross-shard uniqueness
--      requires an external global-ID service or a separate lookup table.
--   3. `created_at` index supports time-range queries and time-based sharding.
--   4. All string lengths are capped to control index size per shard.
-- ==========================================

CREATE TABLE IF NOT EXISTS "users" (
    "id"            BIGINT                   NOT NULL,
    "username"      VARCHAR(64)              NOT NULL,
    "email"         VARCHAR(255)             NOT NULL,
    "phone"         VARCHAR(32),
    "password_hash" VARCHAR(255)             NOT NULL,
    "nickname"      VARCHAR(128)             NOT NULL DEFAULT '',
    "avatar"        VARCHAR(512)             NOT NULL DEFAULT '',
    "gender"        SMALLINT                 NOT NULL DEFAULT 0,   -- 0:unknown 1:male 2:female
    "birthday"      DATE,
    "status"        SMALLINT                 NOT NULL DEFAULT 1,   -- 0:inactive 1:active 2:banned
    "created_at"    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "updated_at"    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "deleted_at"    TIMESTAMP WITH TIME ZONE,

    PRIMARY KEY ("id")
);

-- Local unique indexes (partial index avoids conflict with soft-delete rows)
CREATE UNIQUE INDEX IF NOT EXISTS "idx_users_username_active"
    ON "users" ("username") WHERE "deleted_at" IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS "idx_users_email_active"
    ON "users" ("email") WHERE "deleted_at" IS NULL;

-- phone is nullable; only index non-null + not deleted
CREATE UNIQUE INDEX IF NOT EXISTS "idx_users_phone_active"
    ON "users" ("phone") WHERE "deleted_at" IS NULL AND "phone" IS NOT NULL;

-- Range query support, also useful for time-based sharding
CREATE INDEX IF NOT EXISTS "idx_users_created_at"
    ON "users" ("created_at");

COMMENT ON TABLE  "users" IS '用户表';
COMMENT ON COLUMN "users"."id" IS '用户ID (分布式ID, 分片键)';
COMMENT ON COLUMN "users"."username" IS '用户名';
COMMENT ON COLUMN "users"."email" IS '邮箱';
COMMENT ON COLUMN "users"."phone" IS '手机号';
COMMENT ON COLUMN "users"."password_hash" IS '密码哈希';
COMMENT ON COLUMN "users"."nickname" IS '昵称';
COMMENT ON COLUMN "users"."avatar" IS '头像URL';
COMMENT ON COLUMN "users"."gender" IS '性别 0:未知 1:男 2:女';
COMMENT ON COLUMN "users"."birthday" IS '出生日期';
COMMENT ON COLUMN "users"."status" IS '状态 0:未激活 1:正常 2:封禁';
